### ISSUE TITLE
运行npm run dev后报错

### ISSUE THREAD

**Issue by bzzx** [yanxiaojun617/webpack4-bootstrap4-demo#5]
PS C:\txh\html\webpack4-bootstrap4-demo-master> npm run dev

webpack4-bootstrap4-demo@1.0.0 dev C:\txh\html\webpack4-bootstrap4-demo-master
cross-env NODE_ENV=dev webpack-dev-server --config webpack.config.js --progress

module.js:550
throw err;
^

Error: Cannot find module 'locate-path'
at Function.Module._resolveFilename (module.js:548:15)
at Function.Module._load (module.js:475:25)
at Module.require (module.js:597:17)
at require (internal/module.js:11:18)
at Object. (C:\txh\html\webpack4-bootstrap4-demo-master\node_modules_find-up@3.0.0@find-up\index.js:3:20)
at Module._compile (module.js:653:30)
at Object.Module._extensions..js (module.js:664:10)
at Module.load (module.js:566:32)
at tryModuleLoad (module.js:506:12)
at Function.Module._load (module.js:498:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webpack4-bootstrap4-demo@1.0.0 dev: cross-env NODE_ENV=dev webpack-dev-server --config webpack.config.js --progress
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webpack4-bootstrap4-demo@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\HUIPC\AppData\Roaming\npm-cache_logs\2019-03-07T19_28_08_081Z-debug.log

**Comment by yanxiaojun617** [comment]
应该是你npm i 安装失败了吧，网络不好用手机热点试试
